# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: g:/working_dir/xilinx/PCIe_5GRadio/PCIe_5GRadio_lms7_trx/ip/vivado/pcie_x4/pcie_x4_ex/imports/xilinx_pcie_7x_ep_x4g1.xdc

# IP: ip/pcie_x4/pcie_x4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_x4 || ORIG_REF_NAME==pcie_x4} -quiet] -quiet
