//--------------------------------------------------------------------------------
// Auto-generated by LiteX (75bf6688) on 2022-11-03 16:39:21
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_HUMAN_NAME "Unknown"
#define DMA_CHANNELS 3
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define PCIE_DMA1_READER_INTERRUPT 2
#define PCIE_DMA1_WRITER_INTERRUPT 3
#define PCIE_DMA2_READER_INTERRUPT 4
#define PCIE_DMA2_WRITER_INTERRUPT 5
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "WISHBONE"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#endif
