set_property PACKAGE_PIN D20 [get_ports FPGA_SPI1_MISO]
set_property PROHIBIT true [get_sites AA10]
set_property PROHIBIT true [get_sites AA11]
set_property PROHIBIT true [get_sites AA13]
set_property PROHIBIT true [get_sites AA14]
set_property PROHIBIT true [get_sites AA15]
set_property PROHIBIT true [get_sites AA16]
set_property PROHIBIT true [get_sites AA9]
set_property PROHIBIT true [get_sites AB10]
set_property PROHIBIT true [get_sites AB11]
set_property PROHIBIT true [get_sites AB12]
set_property PROHIBIT true [get_sites AB13]
set_property PROHIBIT true [get_sites AB15]
set_property PROHIBIT true [get_sites AB16]
set_property PROHIBIT true [get_sites AB17]
set_property PROHIBIT true [get_sites T14]
set_property PROHIBIT true [get_sites T15]
set_property PROHIBIT true [get_sites T16]
set_property PROHIBIT true [get_sites U15]
set_property PROHIBIT true [get_sites U16]
set_property PROHIBIT true [get_sites V10]
set_property PROHIBIT true [get_sites V13]
set_property PROHIBIT true [get_sites V14]
set_property PROHIBIT true [get_sites V15]
set_property PROHIBIT true [get_sites W10]
set_property PROHIBIT true [get_sites W11]
set_property PROHIBIT true [get_sites W12]
set_property PROHIBIT true [get_sites W14]
set_property PROHIBIT true [get_sites W15]
set_property PROHIBIT true [get_sites W16]
set_property PROHIBIT true [get_sites Y11]
set_property PROHIBIT true [get_sites Y12]
set_property PROHIBIT true [get_sites Y13]
set_property PROHIBIT true [get_sites Y14]
set_property PROHIBIT true [get_sites Y16]
set_property PROHIBIT true [get_sites Y17]
set_property IOSTANDARD LVCMOS33 [get_ports {BOM_VER[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BOM_VER[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BOM_VER[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BOM_VER[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_VER[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_VER[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_VER[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_VER[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_ADC_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports PCIE_PERSTn]
set_property IOSTANDARD LVCMOS33 [get_ports LMK_CLK]



set_property IOSTANDARD LVCMOS33 [get_ports EXT_GND]


create_interface LMS1
set_property INTERFACE LMS1 [get_ports { LMS1_DIQ1_D[11] LMS1_DIQ1_D[10] LMS1_DIQ1_D[9] LMS1_DIQ1_D[8] LMS1_DIQ1_D[7] LMS1_DIQ1_D[6] LMS1_DIQ1_D[5] LMS1_DIQ1_D[4] LMS1_DIQ1_D[3] LMS1_DIQ1_D[2] LMS1_DIQ1_D[1] LMS1_DIQ1_D[0] LMS1_DIQ2_D[11] LMS1_DIQ2_D[10] LMS1_DIQ2_D[9] LMS1_DIQ2_D[8] LMS1_DIQ2_D[7] LMS1_DIQ2_D[6] LMS1_DIQ2_D[5] LMS1_DIQ2_D[4] LMS1_DIQ2_D[3] LMS1_DIQ2_D[2] LMS1_DIQ2_D[1] LMS1_DIQ2_D[0] LMS1_CORE_LDO_EN LMS1_ENABLE_IQSEL1 LMS1_ENABLE_IQSEL2 LMS1_FCLK1 LMS1_FCLK2 LMS1_MCLK1 LMS1_MCLK2 LMS1_RESET LMS1_RXEN LMS1_TXEN LMS1_TXNRX1 LMS1_TXNRX2 }]
create_interface LMS2
set_property INTERFACE LMS2 [get_ports { LMS2_DIQ1_D[11] LMS2_DIQ1_D[10] LMS2_DIQ1_D[9] LMS2_DIQ1_D[8] LMS2_DIQ1_D[7] LMS2_DIQ1_D[6] LMS2_DIQ1_D[5] LMS2_DIQ1_D[4] LMS2_DIQ1_D[3] LMS2_DIQ1_D[2] LMS2_DIQ1_D[1] LMS2_DIQ1_D[0] LMS2_DIQ2_D[11] LMS2_DIQ2_D[10] LMS2_DIQ2_D[9] LMS2_DIQ2_D[8] LMS2_DIQ2_D[7] LMS2_DIQ2_D[6] LMS2_DIQ2_D[5] LMS2_DIQ2_D[4] LMS2_DIQ2_D[3] LMS2_DIQ2_D[2] LMS2_DIQ2_D[1] LMS2_DIQ2_D[0] LMS2_CORE_LDO_EN LMS2_ENABLE_IQSEL1 LMS2_ENABLE_IQSEL2 LMS2_FCLK1 LMS2_FCLK2 LMS2_MCLK1 LMS2_MCLK2 LMS2_RESET LMS2_RXEN LMS2_TXEN LMS2_TXNRX1 LMS2_TXNRX2 }]
create_interface ADC
set_property INTERFACE ADC [get_ports { ADC_DA_P[6] ADC_DA_P[5] ADC_DA_P[4] ADC_DA_P[3] ADC_DA_P[2] ADC_DA_P[1] ADC_DA_P[0] ADC_DA_N[6] ADC_DA_N[5] ADC_DA_N[4] ADC_DA_N[3] ADC_DA_N[2] ADC_DA_N[1] ADC_DA_N[0] ADC_DB_P[6] ADC_DB_P[5] ADC_DB_P[4] ADC_DB_P[3] ADC_DB_P[2] ADC_DB_P[1] ADC_DB_P[0] ADC_DB_N[6] ADC_DB_N[5] ADC_DB_N[4] ADC_DB_N[3] ADC_DB_N[2] ADC_DB_N[1] ADC_DB_N[0] FPGA_ADC_RESET ADC_CLKOUT_P ADC_CLKOUT_N FPGA_ADC_CLK_P FPGA_ADC_CLK_N }]
create_interface PCIe
set_property INTERFACE PCIe [get_ports { PCIE_PERSTn }]











create_interface MISC
set_property INTERFACE MISC [get_ports { BOM_VER[3] BOM_VER[2] BOM_VER[1] BOM_VER[0] HW_VER[3] HW_VER[2] HW_VER[1] HW_VER[0] EXT_GND }]


set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_N[0]}]





set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ1_D[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS1_DIQ2_D[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_CORE_LDO_EN]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_ENABLE_IQSEL1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_ENABLE_IQSEL2]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_FCLK1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_FCLK2]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_MCLK1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_MCLK2]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_RESET]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_RXEN]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_TXEN]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_TXNRX1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_TXNRX2]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ1_D[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LMS2_DIQ2_D[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_CORE_LDO_EN]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_ENABLE_IQSEL1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_ENABLE_IQSEL2]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_FCLK1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_FCLK2]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_MCLK1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_MCLK2]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_RESET]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_RXEN]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_TXEN]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_TXNRX1]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_TXNRX2]

set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO[0]}]

create_interface FPGA_SPI0
set_property INTERFACE FPGA_SPI0 [get_ports { FPGA_SPI0_LMS1_SS FPGA_SPI0_LMS2_SS FPGA_SPI0_MISO_LMS1 FPGA_SPI0_MISO_LMS2 FPGA_SPI0_MOSI_LMS1 FPGA_SPI0_MOSI_LMS2 FPGA_SPI0_SCLK_LMS1 FPGA_SPI0_SCLK_LMS2 }]

set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_LMS1_SS]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_LMS2_SS]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_MISO_LMS1]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_MISO_LMS2]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_MOSI_LMS1]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_MOSI_LMS2]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_SCLK_LMS1]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI0_SCLK_LMS2]

create_interface FPGA_SPI1
set_property INTERFACE FPGA_SPI1 [get_ports { FPGA_SPI1_SCLK FPGA_SPI1_ADC_SS FPGA_SPI1_DAC_SS FPGA_SPI1_MISO FPGA_SPI1_MOSI }]




create_interface CDCM
set_property INTERFACE CDCM [get_ports { CDCM_RESET_N CDCM_STATUS0 CDCM_STATUS1 CDCM_SYNCN }]
set_property IOSTANDARD LVCMOS25 [get_ports CDCM_RESET_N]
set_property IOSTANDARD LVCMOS25 [get_ports CDCM_STATUS0]
set_property IOSTANDARD LVCMOS25 [get_ports CDCM_STATUS1]
set_property IOSTANDARD LVCMOS25 [get_ports CDCM_SYNCN]

set_property IOSTANDARD LVCMOS33 [get_ports LNA1_BP_M]
set_property IOSTANDARD LVCMOS33 [get_ports LNA1_EN_M]
set_property IOSTANDARD LVCMOS33 [get_ports LNA2_BP_M]
set_property IOSTANDARD LVCMOS33 [get_ports LNA2_EN_M]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW1_RX2_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW1_TRX1R_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW1_TRX1T_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW1_TRX2R_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW1_TRX2T_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW1_TX1_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW2_TRX1R_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW2_TRX1T_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW2_TRX2R_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW2_TRX2T_V1]
set_property IOSTANDARD LVCMOS33 [get_ports RFSW2_TX1_V1]
create_interface RF_CTRL
set_property INTERFACE RF_CTRL [get_ports { LNA1_BP_M LNA1_EN_M LNA2_BP_M LNA2_EN_M RFSW1_RX2_V1 RFSW1_TRX1R_V1 RFSW1_TRX1T_V1 RFSW1_TRX2R_V1 RFSW1_TRX2T_V1 RFSW1_TX1_V1 RFSW2_TRX1R_V1 RFSW2_TRX1T_V1 RFSW2_TRX2R_V1 RFSW2_TRX2T_V1 RFSW2_TX1_V1 }]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI1_ADC_SS]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI1_DAC_SS]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI1_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI1_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SPI1_SCLK]



set_property IOSTANDARD LVCMOS25 [get_ports LMS2_I2C_SCL]
set_property IOSTANDARD LVCMOS25 [get_ports LMS2_I2C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports FAN_CTRL]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_I2C_SDA]
set_property IOSTANDARD LVCMOS25 [get_ports LMS1_I2C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports XO_TUNE_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports PPS_SELECT]
set_property IOSTANDARD LVCMOS33 [get_ports PPS_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports PPS_IN_PREVIOUS]
set_property IOSTANDARD LVCMOS33 [get_ports PPS_IN_EXT]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_RESET_N]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_PPS]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_LCKIND]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_I2C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_I2C_SCL]

set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DB_N[0]}]


set_property PACKAGE_PIN F6 [get_ports PCIE_REFCLK_P]
set_property PACKAGE_PIN J16 [get_ports FPGA_SPI0_LMS1_SS]
set_property PACKAGE_PIN U3 [get_ports FPGA_SPI0_LMS2_SS]
set_property PACKAGE_PIN L15 [get_ports FPGA_SPI0_MISO_LMS1]
set_property PACKAGE_PIN R3 [get_ports FPGA_SPI0_MISO_LMS2]
set_property PACKAGE_PIN M16 [get_ports FPGA_SPI0_MOSI_LMS1]
set_property PACKAGE_PIN R2 [get_ports FPGA_SPI0_MOSI_LMS2]
set_property PACKAGE_PIN M15 [get_ports FPGA_SPI0_SCLK_LMS1]
set_property PACKAGE_PIN T1 [get_ports FPGA_SPI0_SCLK_LMS2]
set_property PACKAGE_PIN J15 [get_ports {LMS1_DIQ1_D[11]}]
set_property PACKAGE_PIN H22 [get_ports {LMS1_DIQ1_D[10]}]
set_property PACKAGE_PIN H15 [get_ports {LMS1_DIQ1_D[9]}]
set_property PACKAGE_PIN H17 [get_ports {LMS1_DIQ1_D[8]}]
set_property PACKAGE_PIN G18 [get_ports {LMS1_DIQ1_D[7]}]
set_property PACKAGE_PIN G17 [get_ports {LMS1_DIQ1_D[6]}]
set_property PACKAGE_PIN G13 [get_ports {LMS1_DIQ1_D[5]}]
set_property PACKAGE_PIN J14 [get_ports {LMS1_DIQ1_D[4]}]
set_property PACKAGE_PIN G15 [get_ports {LMS1_DIQ1_D[3]}]
set_property PACKAGE_PIN G16 [get_ports {LMS1_DIQ1_D[2]}]
set_property PACKAGE_PIN H13 [get_ports {LMS1_DIQ1_D[1]}]
set_property PACKAGE_PIN H14 [get_ports {LMS1_DIQ1_D[0]}]
set_property PACKAGE_PIN K17 [get_ports {LMS1_DIQ2_D[11]}]
set_property PACKAGE_PIN K21 [get_ports {LMS1_DIQ2_D[10]}]
set_property PACKAGE_PIN M22 [get_ports {LMS1_DIQ2_D[9]}]
set_property PACKAGE_PIN L21 [get_ports {LMS1_DIQ2_D[8]}]
set_property PACKAGE_PIN M21 [get_ports {LMS1_DIQ2_D[7]}]
set_property PACKAGE_PIN L16 [get_ports {LMS1_DIQ2_D[6]}]
set_property PACKAGE_PIN M20 [get_ports {LMS1_DIQ2_D[5]}]
set_property PACKAGE_PIN M18 [get_ports {LMS1_DIQ2_D[4]}]
set_property PACKAGE_PIN N22 [get_ports {LMS1_DIQ2_D[3]}]
set_property PACKAGE_PIN N18 [get_ports {LMS1_DIQ2_D[2]}]
set_property PACKAGE_PIN N20 [get_ports {LMS1_DIQ2_D[1]}]
set_property PACKAGE_PIN N19 [get_ports {LMS1_DIQ2_D[0]}]
set_property PACKAGE_PIN J17 [get_ports LMS1_CORE_LDO_EN]
set_property PACKAGE_PIN K13 [get_ports LMS1_ENABLE_IQSEL1]
set_property PACKAGE_PIN K22 [get_ports LMS1_ENABLE_IQSEL2]
set_property PACKAGE_PIN J20 [get_ports LMS1_FCLK1]
set_property PACKAGE_PIN L19 [get_ports LMS1_FCLK2]
set_property PACKAGE_PIN K18 [get_ports LMS1_MCLK1]
set_property PACKAGE_PIN J19 [get_ports LMS1_MCLK2]
set_property PACKAGE_PIN K16 [get_ports LMS1_RESET]
set_property PACKAGE_PIN H20 [get_ports LMS1_RXEN]
set_property PACKAGE_PIN G20 [get_ports LMS1_TXEN]
set_property PACKAGE_PIN J22 [get_ports LMS1_TXNRX1]
set_property PACKAGE_PIN L18 [get_ports LMS1_TXNRX2]
set_property PACKAGE_PIN AB8 [get_ports {LMS2_DIQ1_D[11]}]
set_property PACKAGE_PIN Y7 [get_ports {LMS2_DIQ1_D[10]}]
set_property PACKAGE_PIN Y8 [get_ports {LMS2_DIQ1_D[9]}]
set_property PACKAGE_PIN V5 [get_ports {LMS2_DIQ1_D[8]}]
set_property PACKAGE_PIN U6 [get_ports {LMS2_DIQ1_D[7]}]
set_property PACKAGE_PIN V7 [get_ports {LMS2_DIQ1_D[6]}]
set_property PACKAGE_PIN R6 [get_ports {LMS2_DIQ1_D[5]}]
set_property PACKAGE_PIN Y6 [get_ports {LMS2_DIQ1_D[4]}]
set_property PACKAGE_PIN U7 [get_ports {LMS2_DIQ1_D[3]}]
set_property PACKAGE_PIN Y9 [get_ports {LMS2_DIQ1_D[2]}]
set_property PACKAGE_PIN T6 [get_ports {LMS2_DIQ1_D[1]}]
set_property PACKAGE_PIN V9 [get_ports {LMS2_DIQ1_D[0]}]

set_property PACKAGE_PIN AA5 [get_ports {LMS2_DIQ2_D[11]}]
set_property PACKAGE_PIN T3 [get_ports {LMS2_DIQ2_D[10]}]
set_property PACKAGE_PIN Y1 [get_ports {LMS2_DIQ2_D[9]}]
set_property PACKAGE_PIN AA3 [get_ports {LMS2_DIQ2_D[8]}]
set_property PACKAGE_PIN Y2 [get_ports {LMS2_DIQ2_D[7]}]
set_property PACKAGE_PIN AB2 [get_ports {LMS2_DIQ2_D[6]}]
set_property PACKAGE_PIN Y3 [get_ports {LMS2_DIQ2_D[5]}]
set_property PACKAGE_PIN AB3 [get_ports {LMS2_DIQ2_D[4]}]
set_property PACKAGE_PIN AA1 [get_ports {LMS2_DIQ2_D[3]}]
set_property PACKAGE_PIN W1 [get_ports {LMS2_DIQ2_D[2]}]
set_property PACKAGE_PIN AB1 [get_ports {LMS2_DIQ2_D[1]}]
set_property PACKAGE_PIN W2 [get_ports {LMS2_DIQ2_D[0]}]
set_property PACKAGE_PIN AA6 [get_ports LMS2_CORE_LDO_EN]
set_property PACKAGE_PIN W6 [get_ports LMS2_ENABLE_IQSEL1]
set_property PACKAGE_PIN W5 [get_ports LMS2_ENABLE_IQSEL2]
set_property PACKAGE_PIN T5 [get_ports LMS2_FCLK1]
set_property PACKAGE_PIN Y4 [get_ports LMS2_FCLK2]
set_property PACKAGE_PIN R4 [get_ports LMS2_MCLK1]
set_property PACKAGE_PIN V4 [get_ports LMS2_MCLK2]
set_property PACKAGE_PIN V2 [get_ports LMS2_RESET]
set_property PACKAGE_PIN W9 [get_ports LMS2_RXEN]
set_property PACKAGE_PIN AB6 [get_ports LMS2_TXEN]
set_property PACKAGE_PIN AB7 [get_ports LMS2_TXNRX1]
set_property PACKAGE_PIN AB5 [get_ports LMS2_TXNRX2]
set_property PACKAGE_PIN L14 [get_ports LMS1_I2C_SCL]
set_property PACKAGE_PIN L13 [get_ports LMS1_I2C_SDA]
set_property PACKAGE_PIN U1 [get_ports LMS2_I2C_SCL]
set_property PACKAGE_PIN U2 [get_ports LMS2_I2C_SDA]


set_property IOSTANDARD LVCMOS33 [get_ports LM75_OS]
set_property IOSTANDARD LVCMOS33 [get_ports LMS1_TX1_1_EN]
set_property IOSTANDARD LVCMOS33 [get_ports LMS1_TX1_2_EN]
set_property IOSTANDARD LVCMOS33 [get_ports LMS1_TX2_1_EN]
set_property IOSTANDARD LVCMOS33 [get_ports LMS2_TX1_1_EN]
set_property IOSTANDARD LVCMOS33 [get_ports LMS2_TX1_2_EN]
set_property IOSTANDARD LVCMOS33 [get_ports LMS2_TX2_1_EN]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_SW[0]}]



set_property PACKAGE_PIN P5 [get_ports {ADC_DA_P[6]}]
set_property PACKAGE_PIN B1 [get_ports {ADC_DA_P[5]}]
set_property PACKAGE_PIN K1 [get_ports {ADC_DA_P[4]}]
set_property PACKAGE_PIN H2 [get_ports {ADC_DA_P[3]}]
set_property PACKAGE_PIN E1 [get_ports {ADC_DA_P[2]}]
set_property PACKAGE_PIN G1 [get_ports {ADC_DA_P[1]}]
set_property PACKAGE_PIN C2 [get_ports {ADC_DA_P[0]}]
set_property PACKAGE_PIN L5 [get_ports {ADC_DB_P[6]}]
set_property PACKAGE_PIN R1 [get_ports {ADC_DB_P[5]}]
set_property PACKAGE_PIN M1 [get_ports {ADC_DB_P[4]}]
set_property PACKAGE_PIN N4 [get_ports {ADC_DB_P[3]}]
set_property PACKAGE_PIN M3 [get_ports {ADC_DB_P[2]}]
set_property PACKAGE_PIN K6 [get_ports {ADC_DB_P[1]}]
set_property PACKAGE_PIN J5 [get_ports {ADC_DB_P[0]}]
set_property PACKAGE_PIN H4 [get_ports ADC_CLKOUT_P]
set_property PACKAGE_PIN H3 [get_ports FPGA_ADC_CLK_P]
set_property PACKAGE_PIN M6 [get_ports FPGA_ADC_RESET]
set_property PACKAGE_PIN M5 [get_ports CDCM_RESET_N]
set_property PACKAGE_PIN P6 [get_ports CDCM_STATUS0]
set_property PACKAGE_PIN N5 [get_ports CDCM_STATUS1]
set_property PACKAGE_PIN L6 [get_ports CDCM_SYNCN]

set_property PACKAGE_PIN F20 [get_ports FPGA_SPI1_ADC_SS]
set_property PACKAGE_PIN A21 [get_ports FPGA_SPI1_DAC_SS]
set_property PACKAGE_PIN B21 [get_ports FPGA_SPI1_MOSI]
set_property PACKAGE_PIN D19 [get_ports FPGA_SPI1_SCLK]
set_property PACKAGE_PIN A19 [get_ports {BOM_VER[3]}]
set_property PACKAGE_PIN B18 [get_ports {BOM_VER[2]}]
set_property PACKAGE_PIN B17 [get_ports {BOM_VER[1]}]
set_property PACKAGE_PIN A18 [get_ports {BOM_VER[0]}]
set_property PACKAGE_PIN F19 [get_ports {HW_VER[3]}]
set_property PACKAGE_PIN C18 [get_ports {HW_VER[2]}]
set_property PACKAGE_PIN C17 [get_ports {HW_VER[1]}]
set_property PACKAGE_PIN D17 [get_ports {HW_VER[0]}]
set_property PACKAGE_PIN A13 [get_ports PCIE_PERSTn]
set_property PACKAGE_PIN G21 [get_ports LNA1_BP_M]
set_property PACKAGE_PIN D21 [get_ports LNA1_EN_M]
set_property PACKAGE_PIN E18 [get_ports LNA2_BP_M]
set_property PACKAGE_PIN P20 [get_ports LNA2_EN_M]
set_property PACKAGE_PIN E21 [get_ports RFSW1_RX2_V1]
set_property PACKAGE_PIN G22 [get_ports RFSW1_TRX1R_V1]
set_property PACKAGE_PIN N14 [get_ports RFSW1_TRX1T_V1]
set_property PACKAGE_PIN D22 [get_ports RFSW1_TRX2R_V1]
set_property PACKAGE_PIN F18 [get_ports RFSW1_TRX2T_V1]
set_property PACKAGE_PIN N15 [get_ports RFSW1_TX1_V1]
set_property PACKAGE_PIN P19 [get_ports RFSW2_TRX1R_V1]
set_property PACKAGE_PIN AB22 [get_ports RFSW2_TRX1T_V1]
set_property PACKAGE_PIN AB21 [get_ports RFSW2_TRX2R_V1]
set_property PACKAGE_PIN AA20 [get_ports RFSW2_TRX2T_V1]
set_property PACKAGE_PIN AA21 [get_ports RFSW2_TX1_V1]
set_property PACKAGE_PIN C13 [get_ports {FPGA_GPIO[15]}]
set_property PACKAGE_PIN D14 [get_ports {FPGA_GPIO[14]}]
set_property PACKAGE_PIN C14 [get_ports {FPGA_GPIO[13]}]
set_property PACKAGE_PIN D15 [get_ports {FPGA_GPIO[12]}]
set_property PACKAGE_PIN D16 [get_ports {FPGA_GPIO[11]}]
set_property PACKAGE_PIN C15 [get_ports {FPGA_GPIO[10]}]
set_property PACKAGE_PIN B15 [get_ports {FPGA_GPIO[9]}]
set_property PACKAGE_PIN B16 [get_ports {FPGA_GPIO[8]}]
set_property PACKAGE_PIN F16 [get_ports {FPGA_GPIO[7]}]
set_property PACKAGE_PIN F13 [get_ports {FPGA_GPIO[6]}]
set_property PACKAGE_PIN F14 [get_ports {FPGA_GPIO[5]}]
set_property PACKAGE_PIN F15 [get_ports {FPGA_GPIO[4]}]
set_property PACKAGE_PIN E13 [get_ports {FPGA_GPIO[3]}]
set_property PACKAGE_PIN E14 [get_ports {FPGA_GPIO[2]}]
set_property PACKAGE_PIN E16 [get_ports {FPGA_GPIO[1]}]
set_property PACKAGE_PIN E17 [get_ports {FPGA_GPIO[0]}]
set_property PACKAGE_PIN R14 [get_ports {FPGA_SW[3]}]
set_property PACKAGE_PIN P16 [get_ports {FPGA_SW[2]}]
set_property PACKAGE_PIN R17 [get_ports {FPGA_SW[1]}]
set_property PACKAGE_PIN P17 [get_ports {FPGA_SW[0]}]
set_property PACKAGE_PIN L3 [get_ports CLK100_FPGA_P]
set_property PACKAGE_PIN A20 [get_ports FAN_CTRL]
set_property PACKAGE_PIN K4 [get_ports FPGA_AUXCLK_P]
set_property PACKAGE_PIN T20 [get_ports FPGA_I2C_SCL]
set_property PACKAGE_PIN T21 [get_ports FPGA_I2C_SDA]
set_property PACKAGE_PIN F4 [get_ports FPGA_SPI2_BB_ADC_SS]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI2_BB_ADC_SS]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI2_CDCM_SS]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI2_MISO]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI2_MISO_ADC]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI2_MOSI]
set_property IOSTANDARD LVCMOS25 [get_ports FPGA_SPI2_SCLK]
set_property PACKAGE_PIN F3 [get_ports FPGA_SPI2_CDCM_SS]
set_property PACKAGE_PIN E2 [get_ports FPGA_SPI2_MISO]
set_property PACKAGE_PIN K2 [get_ports FPGA_SPI2_MISO_ADC]
set_property PACKAGE_PIN N2 [get_ports FPGA_SPI2_MOSI]
set_property PACKAGE_PIN P2 [get_ports FPGA_SPI2_SCLK]
set_property PACKAGE_PIN W22 [get_ports GNSS_LCKIND]
set_property PACKAGE_PIN Y21 [get_ports GNSS_PPS]
set_property PACKAGE_PIN U21 [get_ports GNSS_RESET_N]
set_property PACKAGE_PIN W21 [get_ports GNSS_UART_RX]
set_property PACKAGE_PIN Y22 [get_ports GNSS_UART_TX]
set_property PACKAGE_PIN R19 [get_ports LM75_OS]
set_property PACKAGE_PIN W19 [get_ports LMK_CLK]
set_property PACKAGE_PIN B22 [get_ports LMS1_TX1_1_EN]
set_property PACKAGE_PIN C22 [get_ports LMS1_TX1_2_EN]
set_property PACKAGE_PIN E22 [get_ports LMS1_TX2_1_EN]
set_property PACKAGE_PIN Y19 [get_ports LMS2_TX1_1_EN]
set_property PACKAGE_PIN AA19 [get_ports LMS2_TX1_2_EN]
set_property PACKAGE_PIN AB20 [get_ports LMS2_TX2_1_EN]
set_property PACKAGE_PIN AA18 [get_ports PPS_IN_EXT]
set_property PACKAGE_PIN AB18 [get_ports PPS_IN_PREVIOUS]
set_property PACKAGE_PIN V17 [get_ports PPS_OUT]
set_property PACKAGE_PIN W17 [get_ports PPS_SELECT]
set_property PACKAGE_PIN P22 [get_ports XO_TUNE_FPGA]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED1_G]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED1_R]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED2_G]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED2_R]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED3_G]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED3_R]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED4_G]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_LED4_R]
set_property PACKAGE_PIN E19 [get_ports FPGA_LED1_G]
set_property PACKAGE_PIN C19 [get_ports FPGA_LED1_R]
set_property PACKAGE_PIN B20 [get_ports FPGA_LED2_G]
set_property PACKAGE_PIN C20 [get_ports FPGA_LED2_R]
set_property PACKAGE_PIN F21 [get_ports FPGA_LED3_G]
set_property PACKAGE_PIN V18 [get_ports FPGA_LED3_R]
set_property PACKAGE_PIN T18 [get_ports FPGA_LED4_R]

set_property PACKAGE_PIN A15 [get_ports PCIE_SMCLK]
set_property PACKAGE_PIN A16 [get_ports PCIE_SMDAT]
set_property PACKAGE_PIN A14 [get_ports PCIE_WAKEn]
set_property IOSTANDARD LVCMOS33 [get_ports PCIE_SMCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PCIE_SMDAT]
set_property IOSTANDARD LVCMOS33 [get_ports PCIE_WAKEn]

set_property PACKAGE_PIN B13 [get_ports EXT_GND]

set_property CONFIG_MODE SPIx4 [current_design]
set_property PACKAGE_PIN U18 [get_ports FPGA_LED4_G]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property SLEW FAST [get_ports FPGA_SPI0_SCLK_LMS1]
set_property DRIVE 16 [get_ports FPGA_SPI0_SCLK_LMS1]
set_property DRIVE 12 [get_ports FPGA_SPI0_MOSI_LMS2]
set_property DRIVE 16 [get_ports FPGA_SPI0_LMS1_SS]
set_property SLEW FAST [get_ports FPGA_SPI0_LMS1_SS]
set_property DRIVE 16 [get_ports FPGA_SPI0_MOSI_LMS1]
set_property SLEW FAST [get_ports FPGA_SPI0_MOSI_LMS1]
set_property DRIVE 4 [get_ports LMS1_RESET]


set_property SLEW FAST [get_ports {LMS1_DIQ1_D[11]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[10]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[9]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[8]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[7]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[6]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[5]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[4]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[3]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[2]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[1]}]
set_property SLEW FAST [get_ports {LMS1_DIQ1_D[0]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[11]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[10]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[9]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[8]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[7]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[6]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[5]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[4]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[3]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[2]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[1]}]
set_property DRIVE 16 [get_ports {LMS1_DIQ1_D[0]}]
set_property SLEW FAST [get_ports LMS1_FCLK1]
set_property DRIVE 16 [get_ports LMS1_FCLK1]
set_property DRIVE 16 [get_ports LMS1_ENABLE_IQSEL1]
set_property SLEW FAST [get_ports LMS1_ENABLE_IQSEL1]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[11]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[10]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[9]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[8]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[7]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[6]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[5]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[4]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[3]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[2]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[1]}]
set_property DRIVE 16 [get_ports {LMS2_DIQ1_D[0]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[11]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[10]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[9]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[8]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[7]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[6]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[5]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[4]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[3]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[2]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[1]}]
set_property SLEW FAST [get_ports {LMS2_DIQ1_D[0]}]
set_property DRIVE 16 [get_ports LMS2_ENABLE_IQSEL1]
set_property SLEW FAST [get_ports LMS2_ENABLE_IQSEL1]
set_property DRIVE 16 [get_ports LMS2_FCLK1]
set_property SLEW FAST [get_ports LMS2_FCLK1]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK100_FPGA_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[7]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[8]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[9]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[10]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[11]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[12]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[13]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[14]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[15]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[16]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[17]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[18]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[19]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[20]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[21]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[22]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[23]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[24]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[25]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[26]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[27]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[28]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[29]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[30]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_1S_ERROR_TOL[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[7]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[8]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[9]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[10]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[11]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[12]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[13]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[14]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[15]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[16]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[17]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[18]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[19]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[20]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[21]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[22]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[23]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[24]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[25]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[26]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[27]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[28]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[29]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[30]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_100S_ERROR_TOL[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_addr[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[7]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[8]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[9]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[10]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[11]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[12]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[13]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[14]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[15]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[16]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[17]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[18]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[19]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[20]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[21]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[22]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[23]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[24]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[25]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[26]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[27]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[28]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[29]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[30]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/PPS_10S_ERROR_TOL[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[7]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[8]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[9]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[10]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[11]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[12]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[13]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[14]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[15]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[16]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[17]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[18]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[19]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[20]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[21]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[22]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[23]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[24]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[25]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[26]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[27]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[28]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[29]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[30]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_error[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[7]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[8]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[9]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[10]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[11]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[12]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[13]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[14]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[15]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[16]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[17]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[18]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[19]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[20]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[21]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[22]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[23]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[24]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[25]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[26]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[27]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[28]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[29]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[30]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_error[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[0]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[1]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[2]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[3]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[4]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[5]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[6]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[7]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[8]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[9]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[10]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[11]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[12]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[13]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[14]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[15]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[16]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[17]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[18]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[19]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[20]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[21]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[22]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[23]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[24]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[25]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[26]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[27]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[28]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[29]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[30]} {inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_error[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list inst12_mm_rd_datav]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list inst12_mm_wait_req]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_rd_req]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_reset]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/mm_wr_req]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_1s_count_v]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_10s_count_v]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list inst12_limegnss_gpio_top/vctcxo_tamer_top_inst0/vctcxo_tamer_inst0/pps_100s_count_v]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK100_FPGA_BUFG]
