set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[53]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[54]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[57]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[59]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[60]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[63]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[26]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[5]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[48]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[46]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[44]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[39]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[42]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[40]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[33]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[36]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[34]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[24]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[22]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[20]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[49]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[52]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[17]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[27]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[29]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[31]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[1]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[2]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[8]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[9]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[11]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[14]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[55]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[56]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[58]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[61]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[62]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[18]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[0]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[15]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[16]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[50]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[47]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[45]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[38]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[43]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[41]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[32]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[37]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[35]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[19]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[25]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[23]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[21]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[28]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[30]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[3]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[4]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[6]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[7]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[10]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[12]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[13]}]
set_property MARK_DEBUG true [get_nets {inst7_rx_pct_fifo_wdata[51]}]
set_property MARK_DEBUG true [get_nets inst7_rx_pct_fifo_wrreq]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[23]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[30]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[11]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[33]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[24]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[35]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[36]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[39]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[43]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[20]}]
set_property MARK_DEBUG true [get_nets inst6_rx_data_valid]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[37]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[39]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[42]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[46]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[6]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[4]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[1]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[20]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[34]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[18]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[22]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[9]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[35]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[23]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[26]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[11]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[13]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[0]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[2]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[9]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[22]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[31]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[25]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[12]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[15]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[44]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[40]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[37]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[21]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[38]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[14]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[0]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[7]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[12]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[17]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[30]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[24]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[25]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[3]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[6]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[17]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[32]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[28]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[26]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[13]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[45]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[41]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[38]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[18]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[43]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[47]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[3]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[2]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[28]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[16]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[5]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[8]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[32]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[27]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[21]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[4]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[7]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[27]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[16]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[10]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[34]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[29]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[14]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[46]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[42]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[47]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[19]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[36]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[40]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[41]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[44]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[45]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[10]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[33]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[15]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[29]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[19]}]
set_property MARK_DEBUG true [get_nets {inst7_rxtx_top/rx_smpl_fifo_data[31]}]
set_property MARK_DEBUG true [get_nets inst7_rxtx_top/rx_smpl_fifo_wrreq]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[1]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[5]}]
set_property MARK_DEBUG true [get_nets {inst6_rx_data[8]}]

set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[10]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[16]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[18]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[12]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[14]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[24]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[26]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[20]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[22]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[28]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[30]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[11]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[15]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[13]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[23]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[21]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[19]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[31]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[29]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[27]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[25]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[17]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[8]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[9]}]
set_property MARK_DEBUG true [get_nets inst1_pll_top/inst6/s_axi_wvalid]
set_property MARK_DEBUG true [get_nets inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wvalid]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[11]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[9]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[17]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[19]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[13]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[15]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[25]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[27]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[21]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[23]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[29]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[31]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[8]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[14]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[12]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[22]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[20]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[18]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[16]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[30]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[28]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[26]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[24]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst6/s_axi_wdata[10]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wvalid]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[16]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[14]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[15]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[12]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[13]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[31]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[29]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[30]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[27]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[28]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[25]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[26]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[23]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[24]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[21]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[22]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[19]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[20]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[17]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[18]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[8]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[9]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[10]}]
set_property MARK_DEBUG true [get_nets {inst1_pll_top/inst0_tx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/s_axi_wdata[11]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list inst1_pll_top/inst1_rx_pll_top_cyc5/XILINX_MMCM.MMCM_inst1/inst/CLK_CORE_DRP_I/clk_inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/current_state[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 13 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[0]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[1]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[2]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[3]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[4]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[5]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[6]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[7]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[8]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[9]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[10]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[11]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 13 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[0]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[1]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[2]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[3]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[4]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[5]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[6]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[7]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[8]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[9]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[10]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[11]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/next_state[0]} {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/next_state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/BQ_err]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/BI_err]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/AQ_err]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/AI_err]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_h_reg_reg_n_0_[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/diq_l_reg_reg_n_0_[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/IQ_SEL_err]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/wait_cnt_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/wait_cnt_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/wait_cnt_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/wait_cnt_reg_n_0_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list inst6_lms7002_top/inst0_diq2fifo/inst3_smpl_cmp/smpl_err]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets inst1_lms1_rxpll_c1]
