set_property SRC_FILE_INFO {cfile:g:/working_dir/xilinx/PCIe_5GRadio/PCIe_5GRadio_lms7_trx/ip/vivado/pcie_x4/pcie_x4_ex/imports/xilinx_pcie_7x_ep_x4g1.xdc rfile:../../../imports/xilinx_pcie_7x_ep_x4g1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y3 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins pcie_x4_support_i/pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S0]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins pcie_x4_support_i/pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S1]
